version: '3'
services:
  local:
    build: .
    volumes:
      - .:/rightmove-scraper
    environment:
      - TELEGRAM_API_KEY=${TELEGRAM_API_KEY}
      - GSHEETS_RIGHTMOVE_SHEET_ID=${GSHEETS_RIGHTMOVE_SHEET_ID}
