version: '3'
services:
  local:
    build: .
    volumes:
      - .:/rightmove-scraper
    environment:
      - TELEGRAM_API_KEY=${TELEGRAM_API_KEY}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      
