name: Run rightmove searches

on:
  schedule:
    - cron: '0/20 7-23 * * *'
  workflow_dispatch:

jobs:
  run_searches:
    name: Run rightmove and email results
    env: 
      TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
      GSHEETS_RIGHTMOVE_SHEET_ID: ${{ secrets.GSHEETS_RIGHTMOVE_SHEET_ID }}
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.19'

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get -y update
          sudo apt-get install -y google-chrome-stable=114.0.5735.90-1

      - name: Install chromedriver
        run: |
          sudo apt-get install -yqq unzip
          sudo wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          sudo unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/

      - name: Set display port
        run: export DISPLAY=:99

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run searches and update seen listings 
        run: |
          python main.py
      
      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add 'seen_urls.txt' || true
          git add 'openrent_seen_listings.txt' || true
          git commit -m "Updated seen urls file" || true
          git push origin master || true